### ISSUE TITLE
Need help please, I cannt vagrant up repo vagrant-provisioning.

### ISSUE THREAD

**Issue by adityabbg** [justmeandopensource/kubernetes#108]
**Describe the bug**
Hello, am so sorry i got problem here can you help me.
I am new for useing vagrant. 
before this, i watch your video on youtube. i got problem when I try to execute "Vagrant up". Then it show **Authentication failure. Retrying...** 
**Screenshots (if any)**
Bringing machine 'kmaster' up with 'virtualbox' provider...
Bringing machine 'kworker1' up with 'virtualbox' provider...
Bringing machine 'kworker2' up with 'virtualbox' provider...
==> kmaster: Box 'generic/ubuntu2204' could not be found. Attempting to find and install...
    kmaster: Box Provider: virtualbox
    kmaster: Box Version: 4.0.2
==> kmaster: Loading metadata for box 'generic/ubuntu2204'
    kmaster: URL: https://vagrantcloud.com/generic/ubuntu2204
==> kmaster: Adding box 'generic/ubuntu2204' (v4.0.2) for provider: virtualbox
    kmaster: Downloading: https://vagrantcloud.com/generic/boxes/ubuntu2204/versions/4.0.2/providers/virtualbox.box
==> kmaster: Box download is resuming from prior download progress
    kmaster: Download redirected to host: vagrantcloud-files-production.s3-accelerate.amazonaws.com
    kmaster: Calculating and comparing box checksum...
==> kmaster: Successfully added box 'generic/ubuntu2204' (v4.0.2) for 'virtualbox'!
==> kmaster: Importing base box 'generic/ubuntu2204'...
==> kmaster: Matching MAC address for NAT networking...
==> kmaster: Setting the name of the VM: kmaster
==> kmaster: Clearing any previously set network interfaces...
==> kmaster: Preparing network interfaces based on configuration...
    kmaster: Adapter 1: nat
    kmaster: Adapter 2: hostonly
==> kmaster: Forwarding ports...
    kmaster: 22 (guest) => 2222 (host) (adapter 1)
==> kmaster: Running 'pre-boot' VM customizations...
==> kmaster: Booting VM...
==> kmaster: Waiting for machine to boot. This may take a few minutes...
    kmaster: SSH address: 127.0.0.1:2222
    kmaster: SSH username: vagrant
    kmaster: SSH auth method: private key
    kmaster: Warning: Authentication failure. Retrying...
    kmaster: Warning: Authentication failure. Retrying...
    kmaster: Warning: Authentication failure. Retrying...
    kmaster: Warning: Authentication failure. Retrying...
    kmaster: Warning: Authentication failure. Retrying...

**Comment by justmeandopensource** [comment]
Hi @adityabbg 
I have replied to your comment in YouTube. 
Also replying here for anyone facing this issue.

I guess the problem is not with the vagrant box but with your host system. If its genuinely the box problem, it should have happened to me.
The same issue was reported here.
https://github.com/hashicorp/vagrant/issues/8204
Are you running ssh_agent process on your host?
One of them reported running the below command before vagrant up solved the issue. 
`export SSH_AUTH_SOCK=""`
