### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by VishwaJagdale** [justmeandopensource/kubernetes#11]
**Describe the bug**
user@pc:/etc/kubernetes$ kubectl get nodes
The connection to the server localhost:8080 was refused - did you specify the right host or port?

root@pc:~# kubectl get nodes
The connection to the server localhost:8080 was refused - did you specify the right host or port?

[vagrant@kmaster ~]$ kubectl get node
NAME                   STATUS   ROLES    AGE    VERSION
kmaster.example.com    Ready    master   3h2m   v1.16.1
kworker1.example.com   Ready    <none>   159m   v1.16.1
[vagrant@kmaster ~]$ kubectl get rc
No resources found in default namespace.
[vagrant@kmaster ~]$ kubectl get pod
No resources found in default namespace.

[vagrant@kmaster ~]$ ping kworker1
PING kworker1.example.com (172.42.42.101) 56(84) bytes of data.
64 bytes from kworker1.example.com (172.42.42.101): icmp_seq=1 ttl=64 time=0.432 ms
64 bytes from kworker1.example.com (172.42.42.101): icmp_seq=2 ttl=64 time=0.495 ms

--- kworker1.example.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 0.432/0.463/0.495/0.038 ms

[vagrant@kmaster ~]$ ping kworker2
PING kworker2.example.com (172.42.42.102) 56(84) bytes of data.
64 bytes from kworker2.example.com (172.42.42.102): icmp_seq=1 ttl=64 time=0.917 ms
64 bytes from kworker2.example.com (172.42.42.102): icmp_seq=2 ttl=64 time=0.946 ms

--- kworker2.example.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 0.917/0.931/0.946/0.033 ms

**How To Reproduce**

**Expected behavior**

**Screenshots (if any)**

**Environment (please complete the following information):**

**Additional context**

**Comment by justmeandopensource** [comment]
@VishwaJagdale You have to copy the kube config file /etc/kubernetes/admin.conf from the kmaster machine to your local machine at $HOME/.kube/config. Then you will be able to interact with the k8s cluster. Thanks.
