### ISSUE TITLE
Since i don't find where i can contact you personally

### ISSUE THREAD

**Issue by abderraxim** [justmeandopensource/kubernetes#115]
Hello man ,i really love your work and i have been following your videos everyday to setup a full k8s on bare metal with load balancer.
Still facing lot of issues but I'm making progress 
What I'm about to ask you is a real necessity to whole internet because i can't find anywhere a place where it talks about it
I would really be grateful if you do a full tutorial on setup of the following from 0 to production 
- multimaster k8s on bare metal vps
- longhorn as a shared volume provision solution 
- ingress 
- multi domain on same cluster via coredns
- setting dns zone
- deployment on subdomain
I might be wrong on some steps but i guess you understand what I'm talking about
Setting up a subdomain for prometheus for example ..
I really appreciate your work thank you so much.
I have another question : how we can setup customized nameservers on a cluster?
I'm coming from whm cPanel and that was a question of setting a zone with ns records on Powerdns. since we use Coredns how we can implement that structure on kubernetes? Thank you again

**Comment by ak2766** [comment]
Hey @abderraxim - this is an awesome request - from 0 to production.  However, what is production?  Every-one/situation will have a different production requirement.  So, you'll have to define what production is to you.

For demos, deploying nginx into the cluster and showing how to access that service in a browser IS the production environment.

**Comment by a-hahn** [comment]
@abderraxim Perhaps you might take a look at https://homekube.org Its a complete tutorial on how to setup a barematal kubernetes cluster with references to @justmeandopensource  and Techworld  with nanas tutorials explaining the individual steps. Solution covers also cert-manger and automated certificate renewal for DNS01 (wildcard subdomains) with screenshots of a sample DNS service provider.

**Comment by abderraxim** [comment]
Thanks for your feedback, i will check that and get back to you, but before, i have a question or 2.
- where to start to achieve customized nameservers and external dns?
- how can route all the traffic on a single load balancing ip? Like we do on webserver we can design our subdomains or domains to hit the same ip but internally (via zone) hit different folders or in case of k8s different services

**Comment by abderraxim** [comment]
Let me explain how i see the thing:
I shall write necessities randomly and i hope you help me glue them, so let's start. 
- building a cluster with multiple vps spread over different datacenters with multiple masters ( so there is no single point of failure)- minimum 3 to avoid split brain
- routing it via a load balancer which itself has no single point of failure ( as the hosting claims)
- having workers or not ( untaint masters )
- setting customized dns to assign after that domains from different registrars
- setting longhorn ( for k8s <1.25 ) to have shared scheduled space across all vps to avoid again single point of failure 
- let's encrypt all over the cluster
- building dummy wordpress for example and route it to a subdomain 
There might be other points i will be adding them later, thank you again

**Comment by a-hahn** [comment]
> Thanks for your feedback, i will check that and get back to you, but before, i have a question or 2.
> 
>     * where to start to achieve customized nameservers and external dns?
> 
>     * how can route all the traffic on a single load balancing ip? Like we do on webserver we can design our subdomains or domains to hit the same ip but internally (via zone) hit different folders or in case of k8s different services

CoreDns is a good choice for customized nameservers. We use it for providing our internal DNS. e.g. nas.internal.example.com, db.internal.example.com ... On your DNS providers config page you need to add your subdomain nameserver to the list of nameservers e.g. internal.example.com. You need to operate your own coreDNS server which is pretty straightforward and well explained in their tutorials. However to need to open port 53 tcp/udp on your public ip.
Not to confuse this nameserver for your site intrastructure  with your kubernetes clusters nameservers which serve only for cluster internal name resolution.

For single ip loadbalancing we use haproxy as a doorkeeper. I'll add part of our haproxy.cfg file so you might get the idea.

`
#
# https://www.haproxy.com/de/blog/enhanced-ssl-load-balancing-with-server-name-indication-sni-tls-extension/
# https://stackoverflow.com/questions/31262448/can-i-use-wildcard-sni-matching-with-haproxy
# https://stackoverflow.com/questions/40857040/nginx-tcp-forwarding-based-on-domain-name
# https://github.com/opnsense/plugins/issues/1365
# https://medium.com/@olivier.ragain/haproxy-https-load-balancing-on-sni-207c17398d19
#

    global
        log stdout local0 debug

    # Adjust the timeout to your needs
    defaults
      log global
      timeout client 30s
      timeout server 30s
      timeout connect 5s

    # Single VIP
    frontend https
      bind *:443
      mode tcp
      option tcplog

      tcp-request inspect-delay 5s
      tcp-request content accept if { req_ssl_hello_type 1 }

      # NOTICE its req.ssl_sni not req_ssl_sni (deprecated but still valid)
      # NOTICE - do NOT use 'ssl_fc_sni' and 'ssl_fc_sni_end'
      # That is only supported if the certificates are supplied to haproxy e.g. bind *.443 ssl cert ....

      use_backend homekube if { req.ssl_sni -i dashboard.homekube.org }
      use_backend homekube if { req.ssl_sni -i prometheus.homekube.org }
      use_backend homekube if { req.ssl_sni -i grafana.homekube.org }
      use_backend homekube if { req.ssl_sni -i whoami.homekube.org }
      use_backend homekube if { req.ssl_sni -i auth.homekube.org }

      # www.homekube.org is served by github -> @see cname config for homekube.org
      # use_backend rainloop if { req.ssl_sni -i rainloop.homekube.org }
      use_backend raspi if { req.ssl_sni -m end .pi.homekube.org }
      default_backend backend_apache

    # Using SNI to take routing decision
    backend homekube
      mode tcp
      server ingress 192.168.1.200:443

    # Using SNI to take routing decision
    backend raspi
      mode tcp
      server raspi_ingress 192.168.1.48:443

    # Default backend
    # Servers 91 active and 96 backup
    # server apache 192.168.1.96:443
    backend backend_apache
      mode tcp
      server apache 192.168.1.91:443

`

192.168.1.200 and 192.168.1.48 are the entry points for the homekube.org demo cluster metallb configuration.

Hope this helps. Good look !

**Comment by justmeandopensource** [comment]
I will see if I can put together some videos regarding this. I have a backlog of huge list of requested videos. I am going through them in order requested and will take a while to get to this. Cheers.
