### ISSUE TITLE
Containers unstable

### ISSUE THREAD

**Issue by maxoutrage** [justmeandopensource/kubernetes#120]
I followed the guide but there were various containers that were not stable. This link...

https://stackoverflow.com/questions/72567945/issues-with-stability-with-kubernetes-cluster-before-adding-networking

...with this solution solved the stability issues...

sudo sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml

...I added this to the boot strap script to solve my issues.

**Comment by justmeandopensource** [comment]
@maxoutrage thanks for reporting this issue. I know its an old issue. Just wanted to mention that it's all been resolved a while ago.
