### ISSUE TITLE
not able to run vagrant up on ubuntu 22.04 using the vagrant file

### ISSUE THREAD

**Issue by kalavathiy** [justmeandopensource/kubernetes#121]
root@ip-10-192-195-206:~/kala/kubernetes/vagrant-provisioning# vagrant up
Bringing machine 'kmaster' up with 'virtualbox' provider...
Bringing machine 'kworker1' up with 'virtualbox' provider...
Bringing machine 'kworker2' up with 'virtualbox' provider...
==> kmaster: Importing base box 'generic/ubuntu2204'...
Progress: 90%There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["import", "/root/.vagrant.d/boxes/generic-VAGRANTSLASH-ubuntu2204/4.0.2/virtualbox/box.ovf", "--vsys", "0", "--vmname", "generic-ubuntu2204-virtualbox_1667529182963_48853", "--vsys", "0", "--unit", "11", "--disk", "/root/VirtualBox VMs/generic-ubuntu2204-virtualbox_1667529182963_48853/generic-ubuntu2204-virtualbox-disk001.vmdk"]

Stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Interpreting /root/.vagrant.d/boxes/generic-VAGRANTSLASH-ubuntu2204/4.0.2/virtualbox/box.ovf...
OK.
0%...
Progress state: NS_ERROR_INVALID_ARG
VBoxManage: error: Appliance import failed
VBoxManage: error: Code NS_ERROR_INVALID_ARG (0x80070057) - Invalid argument value (extended info not available)
VBoxManage: error: Context: "RTEXITCODE handleImportAppliance(HandlerArg*)" at line 1379 of file VBoxManageAppliance.cpp

**Comment by justmeandopensource** [comment]
@kalavathiy thanks for reporting this issue. I know its too old. But just wanted to mention that all is good with latest code in this repo and tested fine. Thanks
