### ISSUE TITLE
ingress-nginx define the localhost ip as ingress address instead of IP from metallb addresspool

### ISSUE THREAD

**Issue by snup67** [justmeandopensource/kubernetes#123]
**kubernetes version:** 1.23.14
installed by kubespray Inventory template
**metallb version:** 0.13.7
installed by kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/manifests/metallb-native.yaml
**Ingress-nginx version**: v1.5.1 
Installed by _kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.5.1/deploy/static/provider/baremetal/deploy.yaml

The Kubernetes Cluster is **on-premise** base on VM's CentOS 7

When  creating ingress the IP Address that configured is the worker node IP  instead of  the IP from metallb AddressPool
![image](https://user-images.githubusercontent.com/25963382/210905360-862b6997-0920-4ec2-a1f7-faca5dbcf923.png)

Activities that I have done

1. edit ingress-nginx-controller type to LoadBalancer instead of NodePort (Under spec > type )
2. Reinstall ingress-nginx
3. installing ingress in default namespace
4. installing ingress in application namespace

No success.
thanks for the support.

![image](https://user-images.githubusercontent.com/25963382/210905277-b914cbdd-9da7-4b50-804f-4f1c1d0d7d96.png)

**Comment by ak2766** [comment]
Hi there.  The links you've posted for `metallb` and `ingress controller` are broken.  Please update.  I do not want to assume that just copying and pasting will lead me to the document you intended.  Once you've modified and commit the change, please verify that they are going where you expect.

**Comment by snup67** [comment]
I update the links for for metallb and ingress controller

**Comment by snup67** [comment]
Problem solved when I used helm.
The solution:
need to change values before  installing ingress-nginx
enable hostNetwork  
enable hostPort 
![image](https://user-images.githubusercontent.com/25963382/210977180-e9ac1c4b-4992-4c14-85d4-8399df150018.png)

Now the ingress address is correct
![image](https://user-images.githubusercontent.com/25963382/210993179-3921f819-276f-452a-b082-eacca33fcf47.png)

Just that I'm getting 502 Bad Gateway when doing _curl http://10.110.12.214/test_
![image](https://user-images.githubusercontent.com/25963382/210994470-eb2b1ff1-2516-4400-83f8-c699b1ae815c.png)

**Comment by ak2766** [comment]
Good to hear you resolved it.  However, shouldn't that ingress IP be that of the VIP?

**Comment by snup67** [comment]
I think also about it but each time that I configure the VIP IP in **IPAddressPool** the worker node disconnected from cluster, the mode turn to NotReady
![image](https://user-images.githubusercontent.com/25963382/211297597-773a7144-31b6-4f26-84f9-1e89970b2459.png)

**Comment by snup67** [comment]
You can close this

**Comment by ak2766** [comment]
You can actually close this yourself as you are the OP.
