### ISSUE TITLE
Internet issue when running cluster in corporate network 

### ISSUE THREAD

**Issue by vidhya03** [justmeandopensource/kubernetes#124]
**Describe the bug**

When using ```VAGRANT_BOX = "generic/ubuntu2204"``` it boots up successfully, however in company's network, internet is not working.  then changing to ```ubuntu/jammy64``` works perfect. 

**Additional context**

Due to this issue,  initial installation failed. 

I have verified the same scripts working in home, however in office network not working. whereas ```ubuntu/jammy64``` working smoothly.

**Comment by vidhya03** [comment]
Please note i have used windows for my setup.

**Comment by justmeandopensource** [comment]
@vidhya03 thanks for reporting this issue. Might be useful to people in similar situation to yours.
