### ISSUE TITLE
ingress-nginx get 400

### ISSUE THREAD

**Issue by snup67** [justmeandopensource/kubernetes#125]
in kubernetes using ingress-nginx  that installed by helmchart
changing only those parameters
![image](https://user-images.githubusercontent.com/25963382/212285629-6c9d9667-b5fc-4fbd-8b1d-f641633e484a.png)
![image](https://user-images.githubusercontent.com/25963382/212285700-0d646efe-591f-4495-addc-6dae2721a5bb.png)

The ingress located in the namespace of all application
![image](https://user-images.githubusercontent.com/25963382/212281704-6f3e9cb0-5529-44ed-bcda-1694338ab016.png)
ingress describe:
![image](https://user-images.githubusercontent.com/25963382/212282448-5bbba3ee-4848-4bda-ba43-b769ab9280d0.png)

All OK when getting to port 80 - I'm getting the nginx main console
The problem :
all application get 404 for example, looking for network traffic on application test
![image](https://user-images.githubusercontent.com/25963382/212283043-aa84c26e-d972-41e5-a10a-7e80238dbfa4.png)

in application deployment I configured and **didn't helped**
![image](https://user-images.githubusercontent.com/25963382/212283517-3c6ec66b-a0c3-48b1-b0dd-9ba6c55ed399.png)

I check inside container 
![image](https://user-images.githubusercontent.com/25963382/212283730-fa0fd6e4-c702-4263-bcfe-ae27d49bccef.png)
id command gives :   _uid=1000(jenkins) gid=1000(jenkins) groups=1000(jenkins)_

I check the rewrite and is working
![image](https://user-images.githubusercontent.com/25963382/212309734-2a30f983-2196-4f0f-907c-f368a66a21f1.png)

The only issiue I'm thinking about is that using metallb I configured IPAddresspull that not include the IP Adresses of all machine in the clusters, but **I don't know if I'm in correct path to solve that**
![image](https://user-images.githubusercontent.com/25963382/212285190-7616360b-ca60-494c-9757-26cc1af8beeb.png)

Any help will be useful

**Comment by snup67** [comment]
### **some progress - manage to get over the 404 problem**
solve it by adding **annotation nginx.ingress.kubernetes.io/rewrite-target: /** 
but still there is a problem with the rewrite for Jenkins - since Jenkins define the switch between location the rewrite not working well

example:
got the GUI of Jenkins but if click on management I get to nginx console since the rewrite is to main application . I notes that Jenkins management icon redirect to /<host>/management, in my case jenkins-ci/management



> **I think I can't use ingress-nginx controller because he can't handle rewrite well with Jenkins application**


jenkins ingress
![image](https://user-images.githubusercontent.com/25963382/213573452-e3a7fa03-98c8-412a-a763-21667e087841.png)
ingress describe
![image](https://user-images.githubusercontent.com/25963382/213573571-41cda4c6-665b-4546-a0ab-364d17c9fae4.png)

**Comment by justmeandopensource** [comment]
@snup67 thanks for reporting this issue. This was reported a year ago. I am closing this issue as it might not be relevant today. If you still experience this issue please try with the latest version of all the softwares and tools and report it here. Thanks.
