### ISSUE TITLE
kmaster: [TASK 4] Generate and save cluster join command to /joincluster.sh step return  a non-zero exit status

### ISSUE THREAD

**Issue by zarinfam** [justmeandopensource/kubernetes#128]
**Describe the bug**
When I run the `vagrant up` in the `vagrant-provisioning` folder, in the `kmaster: [TASK 4] Generate and save cluster join command to /joincluster.sh` step I get this error:
```
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
When I connect to the `kmaster` using `vagrant ssh kmaster` command and try to run `kmaster: [TASK 4]` manually, I get this error:
```
vagrant@kmaster:~$ kubeadm token create --print-join-command > /joincluster.sh 2>/dev/null
-bash: /joincluster.sh: Permission denied
```

**Expected behavior**
Create cluster!

**Environment (please complete the following information):**
OS: Mac OS (13.1 (22C65))
Vagrant: 2.3.4
VirtualBox: 7.0 (Guest Additions Version: 6.1.32)
latest version of the current repository (6df657f469b252e183c9f75b83f4485572215b31)

![image](https://user-images.githubusercontent.com/1052394/215266477-d7140222-f55c-46d3-93e6-75241de84a5d.png)

**Comment by zarinfam** [comment]
This is more detail about the error:
```
    kmaster: failed to load admin kubeconfig: open /root/.kube/config: no such file or directory
    kmaster: To see the stack trace of this error execute with --v=5 or higher
```

**Comment by zarinfam** [comment]
After removing `>/dev/null 2>&1` from `vagrant-provisioning/bootstrap_kmaster.sh` to see more log, I guess something is wrong with `containerd`:
```
    kmaster: [TASK 1] Pull required containers
    kmaster: I0128 15:46:21.092420    3174 version.go:255] remote version is much newer: v1.26.1; falling back to: stable-1.24
    kmaster: failed to pull image "k8s.gcr.io/kube-apiserver:v1.24.10": output: time="2023-01-28T15:46:21Z" level=fatal msg="validate service connection: CRI v1 image API is not implemented for endpoint \"unix:///var/run/containerd/containerd.sock\": rpc error: code = Unimplemented desc = unknown service runtime.v1.ImageService"
    kmaster: , error: exit status 1
    kmaster: To see the stack trace of this error execute with --v=5 or higher
    kmaster: [TASK 2] Initialize Kubernetes Cluster
    kmaster: I0128 15:46:22.365055    3204 version.go:255] remote version is much newer: v1.26.1; falling back to: stable-1.24
    kmaster:    [WARNING SystemVerification]: missing optional cgroups: blkio
    kmaster: error execution phase preflight: [preflight] Some fatal errors occurred:
    kmaster:    [ERROR CRI]: container runtime is not running: output: time="2023-01-28T15:46:22Z" level=fatal msg="validate service connection: CRI v1 runtime API is not implemented for endpoint \"unix:///var/run/containerd/containerd.sock\": rpc error: code = Unimplemented desc = unknown service runtime.v1.RuntimeService"
    kmaster: , error: exit status 1
    kmaster: [preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
    kmaster: To see the stack trace of this error execute with --v=5 or higher

```

**Comment by zarinfam** [comment]
I found [this PR](https://github.com/justmeandopensource/kubernetes/pull/127) and applied it on the master branch, and it fixed the problem with `containerd`.

**Comment by justmeandopensource** [comment]
@zarinfam Thanks for testing and reporting this issue. Apologies for a very late reply. I know its been a year and I had not had a chance to review outstanding issues in this repo.
I have been tidying up the vagrant scripts and without this containerd patch, it worked fine for me on MacOS. So the latest version of containerd must have been good or the latest version of Ubuntu 22.04 box that I am using must have made a difference.
