### ISSUE TITLE
ClusterAPI

### ISSUE THREAD

**Issue by mohang6770** [justmeandopensource/kubernetes#130]
Hi
 I am reaching out to inquire about the possibility of a video tutorial on K8s cluster API. As someone who is interested in learning more about Kubernetes, I have found all your content to be incredibly informative and helpful.

I understand that creating video content requires time and effort, so I wanted to check if you plan to produce a tutorial on K8s cluster API. I am very excited to learn more about this topic and would love to watch your video.

**Comment by justmeandopensource** [comment]
hi @mohang6770 thanks for your interest in this channel. As you may have noticed, I haven't done any videos over the past year or so. I am trying to get back to posting videos and have a back log of user requests and I will add cluster API to it as well and look into it. Again thanks for your interest.

**Comment by mohang6770** [comment]
Thanks
