### ISSUE TITLE
Create Kubernetes cluster using Vagrant.

### ISSUE THREAD

**Issue by Raf-21** [justmeandopensource/kubernetes#133]
Hi,

First of all, I would like to thank you for the youtube videos created for K8s traefik/middleware. 

I would like to practice more hands-on for K8s(traefik/middleware). How can I setup K8s cluster using Vagrant.  Do you have any documentation/labs that I can follow.

Thanks😊

**Comment by akshayamadhuri** [comment]
@Raf-21 You can use Vagrant for Minikube and Kubernetes  setup you need to download Vagrant on your OS and make sure it contains more than 1 CPU

**Comment by justmeandopensource** [comment]
@Raf-21 Many thanks for your interest in this channel. Apologies for the late reply. Hadn't had a chance to go through the issues recently.
To get some hands-on practice using K8S cluster, you can create one on your local laptop using vagrant. I have many videos on that topic which you can find here (https://www.youtube.com/@justmeandopensource/search?query=vagrant).
The vagrant way of provisioning the cluster can be done on any platform (Linux, Windows or Mac). I keep updating the vagrant scripts to make sure we are using the latest version of k8s and other tools.
If you don't want a fully blown k8s cluster, you can use ones that run on docker containers like Kind, k3d etc. Again I have done videos on these topics as well. Please search in my channel.

Thanks.
