### ISSUE TITLE
LXD Provisioning

### ISSUE THREAD

**Issue by adeel14553** [justmeandopensource/kubernetes#136]
I have been following your homelab, to provision k8 on lxc container. Thats a great approach, I have a question what if I have to use another container runtime like LXE instead of containerd. 
Can you provide some insight on it? What do I have to change, I have run through your bootsrap-kube file. And would love an update on it?

**Comment by justmeandopensource** [comment]
Hi @adeel14553,

Thanks for raising this issue. You are free to use whatever supported container runtime or shim you want with lxc. I only tested containerd with lxc. LXE sounds interesting. I got to try that. I just checked the lxe github repo and there are instructions on how to get it and run it as a shim that you can then configure your kubelet to connect to it. You can add these to the bootstrap scripts etc. I will at some point look into this and if it worked fine in my testing, i may do a video.
