### ISSUE TITLE
LXD provisioing - Error running ProxyServer" err="write /sys/module/nf_conntrack/parameters/hashsize: operation not supported

### ISSUE THREAD

**Issue by Cloud-Mak** [justmeandopensource/kubernetes#144]
Hi Venkat @justmeandopensource 

https://github.com/justmeandopensource/kubernetes/tree/master/lxd-provisioning

Looks like issue with this method now. the kube-proxy remains into crashloop and eventually error 

```
root@master:/etc/kubernetes/manifests# kubectl -n kube-system logs kube-proxy-m6xgl
I0823 17:40:52.912090       1 server_linux.go:69] "Using iptables proxy"
I0823 17:40:52.924381       1 server.go:1062] "Successfully retrieved node IP(s)" IPs=["10.2.7.122"]
I0823 17:40:52.932417       1 conntrack.go:59] "Setting nf_conntrack_max" nfConntrackMax=786432
I0823 17:40:52.933129       1 conntrack.go:90] "Setting conntrack hashsize" conntrackHashsize=196608
E0823 17:40:52.933169       1 server.go:558] "Error running ProxyServer" err="write /sys/module/nf_conntrack/parameters/hashsize: operation not supported"
E0823 17:40:52.933190       1 run.go:74] "command failed" err="write /sys/module/nf_conntrack/parameters/hashsize: operation not supported"
```

I already set value - sysctl -w net.netfilter.nf_conntrack_max=786432. Its not helping at all.
```
root@master:/etc/kubernetes/manifests# kubectl -n kube-system logs kube-proxy-m6xgl
I0823 17:41:22.913788       1 server_linux.go:69] "Using iptables proxy"
I0823 17:41:22.922042       1 server.go:1062] "Successfully retrieved node IP(s)" IPs=["10.2.7.122"]
I0823 17:41:22.930034       1 conntrack.go:59] "Setting nf_conntrack_max" nfConntrackMax=786432
I0823 17:41:22.931151       1 conntrack.go:90] "Setting conntrack hashsize" conntrackHashsize=196608
E0823 17:41:22.931302       1 server.go:558] "Error running ProxyServer" err="write /sys/module/nf_conntrack/parameters/hashsize: operation not supported"
E0823 17:41:22.931432       1 run.go:74] "command failed" err="write /sys/module/nf_conntrack/parameters/hashsize: operation not supported"
```

More info - Host ubu 20.04.6 LTS
LXD - stable 5.21 
I am setting up 1st  master node which is running inside ubuntu 22 lxd container.

I am getting node in ready status (I have already deployed flannel network)

**Comment by Cloud-Mak** [comment]
Update - there is already [PR merged](https://github.com/kubernetes/kubernetes/pull/44919
) for ignoring this /sys/module/nf_conntrack/parameters/hashsize. So not sure how this is till an issue

One more PR - https://github.com/kubernetes/kubernetes/pull/19303

I tried patching kube-proxy ds in kube-system. Just added --conntrack-max-per-core=0 to container of kube-proxy ds. After this the k-proxy pod went int error state. can't see any logs from same pod now. strange


Addtional info - 
Linux does not support writing to /sys/module/nf_conntrack/parameters/hashsize when the writer process is not in the initial network namespace
(https://github.com/torvalds/linux/blob/v4.10/net/netfilter/nf_conntrack_core.c#L1795-L1796).

Usually that's fine. But in some configurations such as (with https://github.com/kinvolk/kubeadm-nspawn) or in current LXD container kube-proxy is in another netns) 

Therefore, check if writing in hashsize is necessary and skip the writing if not.

**Comment by Cloud-Mak** [comment]
Hi All,

Just to update quickly LXD is not what it used to be. Since canonical is forcing you to use it via snap a lot of other issues occours as well.  I eventually ended up switching to incus (its opensource fork of LXD) and works like charm. Way better than LXD.

Coming back to issue of nf_conntrack/parameters/hashsize. After testing it on two different machines, I could see value for net.netfilter.nf_conntrack_max depends on the hardware resource of macine and varies for each machine in order for kube-proxy to work. So once kube-proxy pods fails, get this value for same from the log and set things like below. (On one of my machine it was 786432.)

```
cat >> /etc/sysctl.conf << EOF
#DO NOT REMOVE - else kubeproxy will fail
net.netfilter.nf_conntrack_max=786432
EOF

cat >> /etc/modules << EOF
#DO NOT REMOVE - else kubeproxy will fail
nf_conntrack
EOF
```

Doing above will presist these values across reboots and you will never have issue with kube-proxy.

> root@chennai-incus:~$ sysctl -a | grep nf_conntrack_max
> net.netfilter.nf_conntrack_max = 786432
> net.nf_conntrack_max = 786432
> 

Lastly, I would reccomend switchign to inus. Its worth it.

Makrand

**Comment by Cloud-Mak** [comment]
https://x.com/makrand_san/status/1830897221832708184

I was able to create HA multi master k8s cluser where nodes were incus system containers. LoadBalancing was enabled for control plane nodes. Details in tweet.

**Comment by justmeandopensource** [comment]
@Cloud-Mak Thanks for rasing this issue and the effort in resolving it as well. I am going to look into incus as well. Thanks for suggesting that. 
I have also posted an updated video addressing these issues at https://www.youtube.com/watch?v=3MA29OYc7bg

I think we are good to close this issue for now as we have found a workaround. Thanks for helping.
