### ISSUE TITLE
unable to recognize "dashboard.yaml": no matches for kind "Deployment" in version "apps/v1beta2"

### ISSUE THREAD

**Issue by Anganthier** [justmeandopensource/kubernetes#15]
**Describe the bug**
In Kubernetes V 1.16 the old api style for deployments is obsolete and not supported anymore.

**How To Reproduce**
Use Kubernetes 1.16 or higher

**Expected behavior**

**Screenshots (if any)**

**Environment (please complete the following information):**

**Additional context**

**Comment by Mika67** [comment]
Yes i have the same problem. I don't know a lot of things about K8S . and i have try to replace the apiVersion but don't work

**Comment by justmeandopensource** [comment]
I have updated the apiVersion in the commit 93937b5. Hopefully this should fix the issue. Also, I have released a follow up video where I wasn't using this set of manifests instead using the manifests from the official documentation. Please refere to this video for updates. https://www.youtube.com/watch?v=6MnsSvChl1E
Thanks.
