### ISSUE TITLE
Vagrant provision error

### ISSUE THREAD

**Issue by jaybauson** [justmeandopensource/kubernetes#18]
**Describe the bug**
I tried the vagrant provision for local testing and got the following error:
    kmaster: [TASK 4] Generate and save cluster join command to /joincluster.sh
    kmaster: W1222 03:17:25.649380    8679 validation.go:28] Cannot validate kube-proxy config - no validator is available
    kmaster: W1222 03:17:25.649424    8679 validation.go:28] Cannot validate kubelet config - no validator is available

**How To Reproduce**
simply navigate to vagrant-provision folder and `vagrant up`

**Expected behavior**
There's shouldn't be any error

**Environment (please complete the following information):**
MacOS Catalina
Vagrant 2.2.4
Vbox 6.0.14

**Comment by justmeandopensource** [comment]
@jaybauson despite this error, did you get a working K8s cluster? I noticed this error too. But it didn't affect the cluster provisioning in any ways. I will see if I can figure out how to resolve this. Thanks.

**Comment by DeanPH** [comment]
This is a warning from Kubeadm, not an error...it's just being logged incorrectly to stderr by Kubeadm. See: https://github.com/kubernetes/kubeadm/issues/1913
