### ISSUE TITLE
Support custom k8s master LXC container name

### ISSUE THREAD

**Issue by AshNL** [justmeandopensource/kubernetes#22]
**Describe the bug**
Naming the Kubernetes master LXC container anything other than `kmaster` prevents worker containers from joining the cluster. This is caused by line 91 in [`bootstrap-kube.sh`](https://github.com/justmeandopensource/kubernetes/blob/master/lxd-provisioning/bootstrap-kube.sh) where `kmaster.lxd` is hardcoded.

**How To Reproduce**
Name the master container something else than `kmaster` like `k8s-master` and create a worker container. Run the bootstrap script in both containers. Do `lxc list` and notice how the worker container does not have `flannel.1` in the IPV4 column. `kubectl get nodes` also doesn't show the worker node.

Changing line 91 in the script to the name you have given the master container (`k8s-master.lxd` in my case) fixes the issue.

**Expected behavior**
Worker nodes should be able to join the cluster regardless of the master node container's name.

**Screenshots (if any)**
-

**Environment (please complete the following information):**
Ubuntu: 18.04.3
LXC/LXD: 3.0.3
kubectl client: 1.17.1
kubectl server: 1.17.1

**Additional context**
Fixing this issue is probably as simple as asking the user to enter the name they have given their LXC master container. I have tried to change the script, but I don't know how to implement user input without breaking `cat bootstrap-kube.sh | lxc exec <NAME> bash`. I have 0 experience with shell scripting.

EDIT: perhaps as an argument instead of user input? I'll give it a try later.

**Comment by justmeandopensource** [comment]
Hi, Thanks for using my script. Its just a helper script for getting started. People should adapt/update it to their needs.
