### ISSUE TITLE
Vagrant Provisioning not working.

### ISSUE THREAD

**Issue by kartheek4246** [justmeandopensource/kubernetes#29]
**Describe the bug**
Started seeing issues with vagrant provisioning these days, when we run vagrant up after a while host losing the internet connection and eventually provisioning fails. This is happening everytime.

**How To Reproduce**
Software used:
virtualbox 6.1.4-2
community/vagrant 2.2.7-2 [installed]
OS : 4.19.108-1-MANJARO

**Expected behavior**
Successful cluster provisioning.

**Screenshots (if any)**

**Environment (please complete the following information):**

**Additional context**

**Comment by kartheek4246** [comment]
Using the same scripts from justmeandopensource. Not sure if something is interfering with host network while provisioning and the network coonection keep on dropping when the cluster provision started.

**Comment by kartheek4246** [comment]
By the time docker gets installed, host system loses network connectivity and its getting failed.
==> kmaster: Rsyncing folder: /home/geethsai/kubernetes/vagrant-provisioning/ => /vagrant
==> kmaster: Running provisioner: shell...
    kmaster: Running: /tmp/vagrant-shell20200322-2690-gmqbyf.sh
/opt/vagrant/embedded/gems/gems/vagrant-2.2.7/plugins/provisioners/shell/provisioner.rb:56: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
(eval):1: warning: The called method `detail' is defined here
    kmaster: [TASK 1] Update /etc/hosts file
    kmaster: [TASK 2] Install docker container engine
    kmaster: [TASK 3] Enable and start docker service
    kmaster: Failed to start docker.service: Unit not found.
    kmaster: [TASK 4] Disable SELinux
    kmaster: [TASK 5] Stop and Disable firewalld
    kmaster: [TASK 6] Add sysctl settings
    kmaster: [TASK 7] Disable and turn off SWAP
    kmaster: [TASK 8] Add yum repo file for kubernetes
    kmaster: [TASK 9] Install Kubernetes (kubeadm, kubelet and kubectl)
    kmaster: [TASK 10] Enable and start kubelet service
    kmaster: [TASK 11] Enable ssh password authentication
    kmaster: [TASK 12] Set root password
==> kmaster: Running provisioner: shell...
    kmaster: Running: /tmp/vagrant-shell20200322-2690-18w3s1o.sh
    kmaster: [TASK 1] Initialize Kubernetes Cluster
    kmaster: [TASK 2] Copy kube admin config to Vagrant user .kube directory
    kmaster: cp: cannot stat ‘/etc/kubernetes/admin.conf’: No such file or directory
    kmaster: [TASK 3] Deploy Calico network
    kmaster: -bash: kubectl: command not found
    kmaster: [TASK 4] Generate and save cluster join command to /joincluster.sh
    kmaster: /tmp/vagrant-shell: line 19: kubeadm: command not found
(eval):3: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/opt/vagrant/embedded/gems/gems/vagrant-2.2.7/lib/vagrant/ui.rb:223: warning: The called method `say' is defined here
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by kartheek4246** [comment]
![image](https://user-images.githubusercontent.com/44825499/77272084-57075980-6c7e-11ea-8b2c-72c8c9f45e12.png)

**Comment by justmeandopensource** [comment]
Hmm. I never had this problem.

❯ vboxmanage --version
6.1.10r138449
❯ vagrant --version
Vagrant 2.2.9

It worked for me on different OS and on different combination of vagrant and virtualbox. Its worth giving it a try on a different version of VirtualBox.
