### ISSUE TITLE
Joining ubuntu node to centos cluster

### ISSUE THREAD

**Issue by ukreddy-erwin** [justmeandopensource/kubernetes#30]
Hello sir.. I have setup master on centos by following your video. But when I am trying to join a ubuntu machine as node, I am getting below error.

kubeadm join 10.1.90.159:6443 --token jybm8r.veqignykhisgnki3     --discovery-token-ca-cert-hash sha256:0a4d4025a9397ab3adfebeb4715b0fce297cd0104335d94edbd26e9f6eda608f

W0323 20:11:34.293171    2657 join.go:346] [preflight] WARNING: JoinControlPane.controlPlane settings will be ignored when control-plane flag is not set.
[preflight] Running pre-flight checks
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/

error execution phase preflight: couldn't validate the identity of the API Server: abort connecting to API servers after timeout of 5m0s
To see the stack trace of this error execute with --v=5 or higher

**Comment by justmeandopensource** [comment]
I will test it this weekend and let you know. May I know what version of Centos and Ubuntu you are using?

**Comment by ukreddy-erwin** [comment]
centos 7(and 8) and ubuntu 18+ I tried with

**Comment by justmeandopensource** [comment]
Cool. Thanks. I will give it a try.

**Comment by ukreddy-erwin** [comment]
THere is one more issue.I joined windows node to linux cluster.It is not able to create contianeres on that node.

**Comment by ukreddy-erwin** [comment]
server 2019 node I tried, can you try that too

**Comment by justmeandopensource** [comment]
That will be some other time as I never tried it.

**Comment by justmeandopensource** [comment]
Hi @ukreddy-erwin 
I totally forgot this issue. I made a video which might be helpful. I have CentOS 7 master and added Ubuntu as worker nodes without any issues.
https://www.youtube.com/watch?v=v6Jh2sZClDY
