### ISSUE TITLE
while creating vagrant provisioning we are getting error.

### ISSUE THREAD

**Issue by pravin-07** [justmeandopensource/kubernetes#34]
![image](https://user-images.githubusercontent.com/39874060/82517231-4ff3af00-9b3a-11ea-87ce-1f2602bddb27.png)

**Comment by yunw** [comment]
i got the same error.

**Comment by justmeandopensource** [comment]
Hi, there is nothing wrong with the vagrant file. I have been using it every day basically. It might be just your environment. The cluster initialization didn't happen as expected and thats the reason subsequent steps are failing. I would advise you to remove all the redirection ">/dev/null 2>&1" from bootstrap.sh and bootstrap_kmaster.sh and run it again. You will see where and why exactly its failing. 

Thanks.
