### ISSUE TITLE
Vagrant is using ip's in public space. 172.42.42.10[0-2]

### ISSUE THREAD

**Issue by kinneyd81** [justmeandopensource/kubernetes#35]
The ip's 172.42.42.10[0-2] that is used within the Vagrant file are actually public ip's that resolve to Tmobile.

$ whois 172.42.42.100 |grep OrgName
OrgName:        T-Mobile USA, Inc.

To reproduce, just run vagrant up with the default vagrant file.

Expected behavior. I would have expected something in the 172.16-32.0.0 network space. This is reserved for private networks.

**Comment by justmeandopensource** [comment]
Hi @kinneyd81,
Didn't realize this. I have added a comment to your PR. I am happy to merge this to master if you could update it to 172.16.16.

Thanks

**Comment by ak2766** [comment]
Yeah, see this: [Reserved Address on Wikipedia](https://en.wikipedia.org/wiki/Reserved_IP_addresses)
