### ISSUE TITLE
issue in "vagrant up" command 

### ISSUE THREAD

**Issue by Cryptic-Gemini** [justmeandopensource/kubernetes#39]
kmaster: cp: cannot stat ‘/etc/kubernetes/admin.conf’: No such file or directory
    kmaster: [TASK 3] Deploy flannel network
    kmaster: The connection to the server localhost:8080 was refused - did you specify the right host or port?
    kmaster: [TASK 4] Generate and save cluster join command to /joincluster.sh
    kmaster: failed to load admin kubeconfig: open /root/.kube/config: no such file or directory

**Comment by justmeandopensource** [comment]
Hi @Cryptic-Gemini
It is working fine in my environment and just tested it. It might be something with your environment. 
Basically the kubeadm init command didn't complete successfully and there was problem initializing your cluster. We need to find out why it is failing.
I would suggest you to change below line in bootstrap_kmaster.sh
`kubeadm init --apiserver-advertise-address=172.16.16.100 --pod-network-cidr=192.168.0.0/16 >> /root/kubeinit.log 2>/dev/null`
to
`kubeadm init --apiserver-advertise-address=172.16.16.100 --pod-network-cidr=192.168.0.0/16`
Run 
`vagrant destroy -f`
`vagrant up`
This time you will see more details and would be able to find out the exact cause.

Thanks,
Venkat
