### ISSUE TITLE
kube-scheduler is Unhealthy

### ISSUE THREAD

**Issue by f1l1pp0s** [justmeandopensource/kubernetes#42]
**Describe the bug**
When bootstrapping the Kubernetes Control Plane Kube-Scheduler service fails:
It seems that the ComponentStatus has been deprecated, any workaround on this?

`root@controller-0:~# kubectl get componentstatuses --kubeconfig admin.kubeconfig`
`Warning: v1 ComponentStatus is deprecated in v1.19+`
`NAME                 STATUS      MESSAGE                                                                                 ERROR`
`scheduler            Unhealthy   Get "http://127.0.0.1:10251/healthz": dial tcp 127.0.0.1:10251: ``connect: connection refused`
`controller-manager   Healthy     ok`
`etcd-0                        Healthy     {"health":"true"}`
`etcd-2                        Healthy     {"health":"true"}`
`etcd-1                        Healthy     {"health":"true"}`

**Environment (please complete the following information):**
I am using kubernetes 1.19.0
` kubectl version --client
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
`

**Comment by justmeandopensource** [comment]
Hi, As you found out componenetstatus api is being deprecated. I have had many users experienced this. Despite that, the cluster is fully functional without any issues. So I wouldn't worry too much about it.
