### ISSUE TITLE
The connection to the server localhost:8080 was refused - did you specify the right host or port?

### ISSUE THREAD

**Issue by pushp1997** [justmeandopensource/kubernetes#46]
**Describe the bug**
When I run:
```bash
$ kubectl get nodes
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```
Same error when I run it with sudo as well:
```bash
$ sudo kubectl get nodes
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```
**Environment (please complete the following information):**
Ubuntu 20.04

**Additional context**
After watching the youtube video, I got to know that the I don’t have a .kube directory with the right config in it.
This step is missing in kubernetes/docs/install-cluster-ubuntu-20.md
**Resolution**
```bash
$ mkdir -p $HOME/.kube
$ sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
$ sudo chown $(id -u):$(id -g) $HOME/.kube/config
```

**Comment by pushp1997** [comment]
Hi @justmeandopensource, please review the PR and let me know if further changes are required.
I think this will help others who are stuck at the same step.
Thank you 😄

**Comment by justmeandopensource** [comment]
@pushp1997 Thanks for this PR. Basicaly in all my videos, I encourage people to connect to the cluster from the local machine and I have explained how to copy the kube config file to local machine. I don't want them to use kubectl in the master nodes. 
But anyways, this will be of help to those who want to use it on the master node. 
I will review this shortly and merge it. 
Thanks for your effort. Cheers.

**Comment by pushp1997** [comment]
Also, thanks for all your video tutorials on YouTube.

A happy subscriber from India! 😄 👍🏽

**Comment by nitin194** [comment]
> **Describe the bug**
> When I run:
> 
> ```shell
> $ kubectl get nodes
> The connection to the server localhost:8080 was refused - did you specify the right host or port?
> ```
> 
> Same error when I run it with sudo as well:
> 
> ```shell
> $ sudo kubectl get nodes
> The connection to the server localhost:8080 was refused - did you specify the right host or port?
> ```
> 
> **Environment (please complete the following information):**
> Ubuntu 20.04
> 
> **Additional context**
> After watching the youtube video, I got to know that the I don’t have a .kube directory with the right config in it.
> This step is missing in kubernetes/docs/install-cluster-ubuntu-20.md
> **Resolution**
> 
> ```shell
> $ mkdir -p $HOME/.kube
> $ sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
> $ sudo chown $(id -u):$(id -g) $HOME/.kube/config
> ```

Thanks ... this helped me to solve the same problem
