### ISSUE TITLE
 "Peer's Certificate issuer is not recognized."

### ISSUE THREAD

**Issue by kamal2222ahmed** [justmeandopensource/kubernetes#5]
**Describe the bug**
since I am behind our corporate vpn, the access to internet seems to be restricted from within vagrant , unless I install our corporate ssl cert

**How To Reproduce**

vagrant up
**Expected behavior**

**Screenshots (if any)**
kmaster: [TASK 4] Disable SELinux
    kmaster: [TASK 5] Stop and Disable firewalld
    kmaster: [TASK 6] Add sysctl settings
    kmaster: [TASK 7] Disable and turn off SWAP
    kmaster: [TASK 8] Add yum repo file for kubernetes
    kmaster: [TASK 9] Install Kubernetes (kubeadm, kubelet and kubectl)
    kmaster: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno 14] curl#60 - "Peer's Certificate issuer is not recognized."
    kmaster: Trying other mirror.
    kmaster: It was impossible to connect to the CentOS servers.
    kmaster: This could mean a connectivity issue in your environment, such as the requirement to configure a proxy,
    kmaster: or a transparent proxy that tampers with TLS security, or an incorrect system clock.
    kmaster: You can try to solve this issue by using the instructions on https://wiki.centos.org/yum-errors
    kmaster: If above article doesn't help to resolve this issue please use https://bugs.centos.org/.
    kmaster:
    kmaster:
    kmaster:  One of the configured repositories failed (Kubernetes),
    kmaster:  and yum doesn't have enough cached data to continue. At this point the only
    kmaster:  safe thing yum can do is fail. There are a few ways to work "fix" this:
    kmaster:
    kmaster:      1. Contact the upstream for the repository and get them to fix the problem.
    kmaster:
    kmaster:      2. Reconfigure the baseurl/etc. for the repository, to point to a working
    kmaster:         upstream. This is most often useful if you are using a newer
    kmaster:         distribution release than is supported by the repository (and the
    kmaster:         packages for the previous distribution release still work).
    kmaster:
    kmaster:      3. Run the command with the repository temporarily disabled
    kmaster:             yum --disablerepo=kubernetes ...
    kmaster:
    kmaster:      4. Disable the repository permanently, so yum won't use it by default. Yum
    kmaster:         will then just ignore the repository until you permanently enable it
    kmaster:         again or use --enablerepo for temporary usage:
    kmaster:
    kmaster:             yum-config-manager --disable kubernetes
    kmaster:         or
    kmaster:             subscription-manager repos --disable=kubernetes
    kmaster:
    kmaster:      5. Configure the failing repository to be skipped, if it is unavailable.
    kmaster:         Note that yum will try to contact the repo. when it runs most commands,
    kmaster:         so will have to try and fail each time (and thus. yum will be be much
    kmaster:         slower). If it is a very temporary problem though, this is often a nice
    kmaster:         compromise:
    kmaster:
    kmaster:             yum-config-manager --save --setopt=kubernetes.skip_if_unavailable=true
    kmaster:
    kmaster: failure: repodata/repomd.xml from kubernetes: [Errno 256] No more mirrors to try.
    kmaster: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno 14] curl#60 - "Peer's Certificate issuer is not recognized."
    kmaster: [TASK 10] Enable and start kubelet service
    kmaster: Failed to execute operation: No such file or directory
    kmaster: Failed to start kubelet.service: Unit not found.
    kmaster: [TASK 11] Enable ssh password authentication
    kmaster: [TASK 12] Set root password
    kmaster: Changing password for user root.
    kmaster: passwd: all authentication tokens updated successfully.
==> kmaster: Running provisioner: shell...
    kmaster: Running: /var/folders/jr/kc1rdmj10jb4p1hrw77zttq00000gn/T/vagrant-shell20190427-41761-wmvcx4.sh
    kmaster: [TASK 1] Initialize Kubernetes Cluster
    kmaster: /tmp/vagrant-shell: line 5: kubeadm: command not found
    kmaster: [TASK 2] Copy kube admin config to Vagrant user .kube directory
    kmaster: cp: cannot stat ‘/etc/kubernetes/admin.conf’: No such file or directory
    kmaster: [TASK 3] Deploy flannel network
    kmaster: -bash: kubectl: command not found
    kmaster: [TASK 4] Generate and save cluster join command to /joincluster.sh
    kmaster: /tmp/vagrant-shell: line 19: kubeadm: command not found
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by justmeandopensource** [comment]
@kamal2222ahmed The vagrant up command requires a working internet connection to download Kubernetes pacakges. If you can't access the internet, you could set up a local centos mirros in your environment.

Thanks,
Venkat
