### ISSUE TITLE
Unable to start the pod when using daemonset

### ISSUE THREAD

**Issue by dhandma** [justmeandopensource/kubernetes#51]
Hi All,
I am using the configuration provided by you for nginx-ingress. After creating daemonsets, I am getting below error:

W1109 06:15:33.387442       1 main.go:284] The '-use-ingress-class-only' flag will be deprecated and has no effect on versions of kubernetes >= 1.18.0. Processing ONLY resources that have the 'ingressClassName' field in Ingress equal to the class.
F1109 06:15:33.390807       1 main.go:288] Error when getting IngressClass nginx: ingressclasses.networking.k8s.io "nginx" is forbidden: User "system:serviceaccount:nginx-ingress:nginx-ingress" cannot get resource "ingressclasses" in API group "networking.k8s.io" at the cluster scope

**Comment by niraj1234567890** [comment]
@dhandma I am also facing the same issue. Did you able to get it resolved? If yes then let me know the process. Thanks in advance

**Comment by servetzeybek** [comment]
Hi @dhandma  
did you solve it?

**Comment by donevgoran** [comment]
Hi,

His tutorial is recorded at March 2019, and working on the older version of nginx-ingress and kubernetes, from then to now has a lot of changes.

Here is instruction how you can install nginx-ingress.
https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-manifests/

I believe that this can help you.

Thanks
