### ISSUE TITLE
docker based cluster fails with health check on https://127.0.0.1:10259/healthz

### ISSUE THREAD

**Issue by gh4dp** [justmeandopensource/kubernetes#55]
Hi All,
I was able to create perfectly healthy cluster in the past.
Recent attempts failed though, visible if you run "kubectl get componentstatus"

> [vagrant@kmaster ~]$ kubectl get componentstatus
Warning: v1 ComponentStatus is deprecated in v1.19+
NAME                 STATUS      MESSAGE                                                                                       ERROR
scheduler            Unhealthy   Get "http://127.0.0.1:10251/healthz": dial tcp 127.0.0.1:10251: connect: connection refused   
controller-manager   Unhealthy   Get "http://127.0.0.1:10252/healthz": dial tcp 127.0.0.1:10252: connect: connection refused   
etcd-0               Healthy     {"health":"true"}                                                                             
[vagrant@kmaster ~]$ 

**I tried to modify manifest file by replacing --bind-address from 127.0.0.1 to 172.16.16.100 and "describe" does show correct urls for checks but "componentstatus" side still shows 127... IP.
Am I doing anything wrong?**

Below is the describe on the component, as seen the url now points to 172.16.16.100 but the componentstatus still returns url of 127.0.0.1

>      Requests:
>       cpu:        100m
>     Liveness:     http-get https://172.16.16.100:10259/healthz delay=10s timeout=15s period=10s #success=1 #failure=8
>     Startup:      http-get https://172.16.16.100:10259/healthz delay=10s timeout=15s period=10s #success=1 #failure=24
>     Environment:  <none>
>     Mounts:
>       /etc/kubernetes/scheduler.conf from kubeconfig (ro)
> Conditions:
>   Type              Status
>   Initialized       True 
>   Ready             True 
>   ContainersReady   True 
>   PodScheduled      True 
> Volumes:
>   kubeconfig:
>     Type:          HostPath (bare host directory volume)
>     Path:          /etc/kubernetes/scheduler.conf
>     HostPathType:  FileOrCreate
> QoS Class:         Burstable
> Node-Selectors:    <none>
> Tolerations:       :NoExecute op=Exists
> Events:
>   Type     Reason                  Age    From     Message
>   ----     ------                  ----   ----     -------
>   Normal   Pulled                  9m22s  kubelet  Container image "k8s.gcr.io/kube-scheduler:v1.20.1" already present on machine
>   Normal   Created                 9m22s  kubelet  Created container kube-scheduler
>   Normal   Started                 9m22s  kubelet  Started container kube-scheduler
>   Warning  FailedCreatePodSandBox  9m22s  kubelet  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create a sandbox for pod "kube-scheduler-kmaster.example.com": Error response from daemon: Conflict. The container name "/k8s_POD_kube-scheduler-kmaster.example.com_kube-system_6085d2b9fd8b0ad13cdee3fce30ee195_0" is already in use by container "07b1511d57b84d6b74802576cb157ce8b69cdc7fe15efd9235bafa629cac18be". You have to remove (or rename) that container to be able to reuse that name.
>   Normal   SandboxChanged          5m28s  kubelet  Pod sandbox changed, it will be killed and re-created.
>   Normal   Pulled                  5m28s  kubelet  Container image "k8s.gcr.io/kube-scheduler:v1.20.1" already present on machine
>   Normal   Created                 5m28s  kubelet  Created container kube-scheduler
>   Normal   Started                 5m28s  kubelet  Started container kube-scheduler
> [vagrant@kmaster ~]$ 
>

**Comment by khann-adill** [comment]
Try with this fully automated setting up k8s cluster with lots of addon

https://github.com/khann-adill/kubernetes-ansible
