### ISSUE TITLE
[LXD/LXC] No IPv4 using k8s profile

### ISSUE THREAD

**Issue by ratnadeep007** [justmeandopensource/kubernetes#7]
**Describe the bug**
I am trying to create kubernetes cluster using lxc/lxd machine containers following the video. I used same Vagrantfile to create the virtual machine using ubuntu 18.04. When creating container using default profile it assigns a IPv4 address while using k8s profile it's IPv6 and not IPv4 address.

**Expected behavior**
Using k8s profile it should assign IPv4 address.

**Screenshots (if any)**
![lxc_profiles](https://user-images.githubusercontent.com/17860233/64364205-060c7c80-d030-11e9-9cbd-4020273c02bd.png)
![lxc_list](https://user-images.githubusercontent.com/17860233/64364219-0c025d80-d030-11e9-9879-94b5dc2acd25.png)

**Environment (please complete the following information):**
Vagrant environment from: ![Vagrant file](https://github.com/justmeandopensource/vagrant/blob/master/vagrantfiles/ubuntu18/Vagrantfile)

**Comment by MatthiasHertel** [comment]
@ratnadeep007 

u can disable ipv6 on lxc network "globally" with:

```
lxc network set lxdbr0 ipv6.address none
```

maybe it helps and after that u can adjust ipv4 manually:

```
lxc stop kworker1
lxc network attach lxdbr0 kworker1 eth0 eth0
lxc config device set kworker1 eth0 ipv4.address 10.58.137.144
lxc start kworker1
```
