### ISSUE TITLE
hekei-cli No such file or directory

### ISSUE THREAD

**Issue by leiw324** [justmeandopensource/kubernetes#88]
**Describe the bug**
Hello, I am trying heketi device add from this video, but  the error is Error: Initializing device /dev/vdb failed (already initialized or contains data?): /bin/bash: /usr/sbin/lvm: No such file or directory

**How To Reproduce**
 heketi-cli device add --name /dev/vdb --node 5bb04c54600dcbf37e616bef3bcf9996
 
 Also, I tried wipefs -af /dev/vdb with no error, but no luck.

**Expected behavior**
I wants to add the device to heketi.

**Screenshots (if any)**
![image](https://user-images.githubusercontent.com/33790160/142723880-612dfcae-3740-4af9-be36-7b514df9bdff.png)
![image](https://user-images.githubusercontent.com/33790160/142723884-23c56c7f-cb72-4074-afae-324c4b3892f1.png)

**Environment (please complete the following information):**
Ubuntu 18.04.4 LTS

**Additional context**

**Comment by jav333** [comment]
Can someone help?

**Comment by justmeandopensource** [comment]
The actual error states that /usr/sbin/lvm is missing. This binary comes from lvm2 package.
Try installing lvm2 package and then give it a try.
```
sudo apt install -y lvm2
```

**Comment by deba10106** [comment]
I'm also facing the same issue. I already had lvm2 installed but the package seems to be in a different location. Not sure if anyone has a solution to this!
