### ISSUE TITLE
can you share file network config.

### ISSUE THREAD

**Issue by bboyadao** [justmeandopensource/kubernetes#93]
it's in https://github.com/justmeandopensource/kubernetes/tree/master/vagrant-provisioning

I use i3 as you, and using NetworkManager.service
and can not assign static ip.
![Screenshot_2022-01-25-03:07:22-1643054842](https://user-images.githubusercontent.com/25122065/150862826-4f956f51-2c1b-41da-894c-de26416e8f25.png)
![Screenshot_2022-01-25-03:09:36-1643054976](https://user-images.githubusercontent.com/25122065/150862816-88b5da8f-5d42-4403-9d4a-b3cf11683ad0.png)
I found NetworkManager using dhcp run as backend, so i will try to switch to netctl. 
can you share your config ?
Thanks.

**Comment by bhattacharyyasom** [comment]
i am getting this same issue on a mac. Any luck ?

**Comment by paulokinjo** [comment]
The error message says it all.
Go to 
https://www.virtualbox.org/manual/ch06.html#network_hostonly

In resume:
Just edit or create the file **/etc/vbox/networks.conf** and change to:

<pre>* 0.0.0.0/0 ::/0</pre>

**Comment by bhattacharyyasom** [comment]
@paulokinjo 

I did that and am getting this message : 

> There was an error while executing `VBoxManage`, a CLI used by Vagrant
> for controlling VirtualBox. The command and stderr is shown below.
> 
> Command: ["hostonlyif", "create"]
> 
> Stderr: 0%...
> Progress state: NS_ERROR_FAILURE
> VBoxManage: error: Failed to create the host-only adapter
> VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
> VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
> VBoxManage: error: Context: "RTEXITCODE handleCreate(HandlerArg *)" at line 95 of file VBoxManageHostonly.cpp
>

**Comment by bhattacharyyasom** [comment]
@paulokinjo  thank you . Worked wonders !  Onwards to try CKAD. :D Appreciate your time.

**Comment by Sajjadhz** [comment]
@bboyadao 
* 10.0.0.0/8 192.168.0.0/16 172.16.0.0/16

**Comment by justmeandopensource** [comment]
I have this in my /etc/vbox/networks.conf and it works fine.
```
* 10.0.0.0/8 192.168.0.0/16 172.16.16.0/24
* 2001::/64
```
Thanks @paulokinjo for helping.

**Comment by roccqqck** [comment]
I encountered this issue recently as well.

I simply replace the IPs of Vagrantfile from 172.16.16.x with 192.168.56.x.

For example, `172.16.16.10#{i}` -> `192.168.56.10#{i}`
